name: Publish ModuleSite on gh-pages

on:
  # Trigger the workflow on push only for master branch
  push:
    branches:
      - master

jobs:
  # Trigger job i.e. build and run on the latest version of ubuntu
  build:
    runs-on: ubuntu-latest
    # Templates for building and releasing ModuleSite
    steps:
      # Template that allows deploy.yml file to access github project when running on its own environment
      - uses: actions/checkout@v2
      # Template to build and release ModuleSite
      - uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          access-token: ${{ secrets.MODULESITE_DEPLOY_TOKEN }}
          # Output after building the ModuleSite will be pushed on deploy branch
          deploy-branch: deploy
          # Additional arguments that get passed to gatsby build 
          gatsby-args: --prefix-paths
